import type { Metadata } from "next";
import "./globals.css";

import { ChakraProvider } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Todolist.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
